version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/.github/actions/setup'
    schedule:
      interval: 'monthly'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      actions-minor-patch:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      deps-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
