name: 'setup'
description: 'setup node and node_modules'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - uses: flatt-security/setup-takumi-guard-npm@v1
    - name: Setup
      run: pnpm install --frozen-lockfile
      shell: bash
