export const EffectTrigger = {
  StartWave: 'start_wave',
  EndWave: 'end_wave',
  StartRound: 'start_round',
  Idle: 'idle',
  Idle2Times: 'idle_2_times',
  Kill: 'kill',
  BeKilled: 'be_killed',
  AllyKilled: 'ally_killed',
  EnemyKilled: 'enemy_killed',
  UseAnyActive: 'use_any_active',
  UseThisActive: 'use_this_active',
  Attack: 'attack',
  Attacked: 'attacked',
  BeAttacked: 'be_attacked',
  Hit: 'hit',
  HitAnyActive: 'hit_any_active',
  HitVitalSpot: 'hit_vital_spot',
  BeHit: 'be_hit',
  BeHitFireActive: 'be_hit_fire_active',
  BeHitIceActive: 'be_hit_ice_active',
  BeHitElectricActive: 'be_hit_electric_active',
  Evade: 'evade',
  Critical: 'critical',
  Revive: 'revive',
  Moved: 'moved'
} as const;
export type EffectTrigger = typeof EffectTrigger[keyof typeof EffectTrigger]

export const EffectActivationState = {
  HpGreaterOrEqual: 'hp_greater_or_equal',
  HpLessOrEqual: 'hp_less_or_equal',
  HpGreaterThan: 'hp_greater_than',
  HpLessThan: 'hp_less_than',
  HpRateLessThanSelf: 'hp_rate_less_than_self',
  Protected: 'protected',
  Effected: 'effected',
  Tagged: 'tagged',
  StackGe: 'stack_ge',
  Form: 'form',
  Equipped: 'equipped',
  InFrontLine: 'in_front_line',
  InMidLine: 'in_mid_line',
  InBackLine: 'in_back_line',
  InSquad: 'in_squad',
  Unit: 'unit',
  EffectedBy: 'effected_by'
} as const;
export type EffectActivationState = typeof EffectActivationState[keyof typeof EffectActivationState]

export const Effect = {
  AdditionalDamage: 'additional_damage',
  Enmity: 'enmity',
  Merciless: 'merciless',
  AdditionalFireDamage: 'additional_fire_damage',
  AdditionalIceDamage: 'additional_ice_damage',
  AdditionalElectricDamage: 'additional_electric_damage',
  FireResistUp: 'fire_resist_up',
  FireResistDown: 'fire_resist_down',
  IceResistUp: 'ice_resist_up',
  IceResistDown: 'ice_resist_down',
  ElectricResistUp: 'electric_resist_up',
  ElectricResistDown: 'electric_resist_down',
  FixedDamage: 'fixed_damage',
  DamageOverTime: 'damage_over_time',
  FixedDamageOverTime: 'fixed_damage_over_time',
  FixedFireDamageOverTime: 'fixed_fire_damage_over_time',
  FixedIceDamageOverTime: 'fixed_ice_damage_over_time',
  FixedElectricDamageOverTime: 'fixed_electric_damage_over_time',
  AntiLightType: 'anti_light_type',
  AntiHeavyType: 'anti_heavy_type',
  AntiFlyingType: 'anti_flying_type',
  HpUp: 'hp_up',
  AtkUp: 'atk_up',
  AtkDown: 'atk_down',
  DefUp: 'def_up',
  DefDown: 'def_down',
  AccUp: 'acc_up',
  AccDown: 'acc_down',
  EvaUp: 'eva_up',
  EvaDown: 'eva_down',
  CriUp: 'cri_up',
  CriDown: 'cri_down',
  SpdUp: 'spd_up',
  SpdDown: 'spd_down',
  ApUp: 'ap_up',
  ApDown: 'ap_down',
  SetAp: 'set_ap',
  StatusResistUp: 'status_resist_up',
  StatusResistDown: 'status_resist_down',
  ExpUp: 'exp_up',
  RangeUp: 'range_up',
  RangeDown: 'range_down',
  DefensePenetration: 'defense_penetration',
  DamageTakenIncreased: 'damage_taken_increased',
  DamageReduction: 'damage_reduction',
  MinimizeDamage: 'minimize_damage',
  NullifyDamage: 'nullify_damage',
  Barrier: 'barrier',
  BattleContinuation: 'battle_continuation',
  FormChange: 'form_change',
  FormRelease: 'form_release',
  TagStack: 'tag_stack',
  TagUnstack: 'tag_unstack',
  TagRelease: 'tag_release',
  AllBuffRemoval: 'all_buff_removal',
  AllDebuffRemoval: 'all_debuff_removal',
  EffectRemoval: 'effect_removal',
  PreventsEffect: 'prevents_effect',
  ActivationRatePercentageUp: 'activation_rate_percentage_up',
  ColumnProtect: 'column_protect',
  RowProtect: 'row_protect',
  TargetProtect: 'target_protect',
  FollowUpAttack: 'follow_up_attack',
  Counterattack: 'counterattack',
  IgnoreBarrierDr: 'ignore_barrier_dr',
  IgnoreDr: 'ignore_dr',
  IgnoreProtect: 'ignore_protect',
  Pull: 'pull',
  Push: 'push',
  Reconnaissance: 'reconnaissance',
  Marked: 'marked',
  Provoked: 'provoked',
  Immovable: 'immovable',
  Silenced: 'silenced',
  Stunned: 'stunned',
  RefundAp: 'refund_ap',
  AttackCritical: 'attack_critical',
  CounterattackCritical: 'counterattack_critical',
  DeployDefensiveWall: 'deploy_defensive_wall',
  AMG11Construction: 'amg_11_construction',
  DeployRabbitDField: 'deploy_rabbit_d_field',
  SummonHologramTiger: 'summon_hologram_tiger'
} as const;
export type Effect = typeof Effect[keyof typeof Effect]

export type EquipmentEffectOnly = typeof Effect['HpUp']
