export const EffectTrigger = {
  StartWave: 'start_wave',
  EndWave: 'end_wave',
  StartRound: 'start_round',
  Idle: 'idle',
  Kill: 'kill',
  BeKilled: 'be_killed',
  AllyKilled: 'ally_killed',
  EnemyKilled: 'enemy_killed',
  UseAnyActive: 'use_any_active',
  UseThisActive: 'use_this_active',
  UseActive2: 'use_active_2',
  Attack: 'attack',
  Attacked: 'attacked',
  BeAttacked: 'be_attacked',
  FollowUpAttack: 'follow_up_attack',
  Hit: 'hit',
  HitFireActive: 'hit_fire_active',
  HitAnyActive: 'hit_any_active',
  HitActive2: 'hit_active_2',
  HitVitalSpot: 'hit_vital_spot',
  Missed: 'missed',
  BeHit: 'be_hit',
  BeHitFireActive: 'be_hit_fire_active',
  BeHitIceActive: 'be_hit_ice_active',
  BeHitElectricActive: 'be_hit_electric_active',
  Evade: 'evade',
  Critical: 'critical',
  Counter: 'counter',
  Revive: 'revive'
} as const;
export type EffectTrigger = typeof EffectTrigger[keyof typeof EffectTrigger]
