export type SkillEffectTagStackValue = 1 | 2 | 3 | 5 | 6

export type SkillEffectTag =
  'ignite' |
  'wet' |
  'freeze' |
  'corrosion' |
  'overloaded' |
  'plasma_generator' |
  'frost_storm' |
  'electric_charge' |
  'sadistic_chef' |
  'practice_begins' |
  'output_increase' |
  'masochistic_nature' |
  'sadistic_nature' |
  'revenger' |
  'alert_mode' |
  'undying_will' |
  'yummy' |
  'counterattack_initiation' |
  'fire_net_building' |
  'rifled_mortar' |
  'bullet_curtain_max' |
  'bullet_curtain_many' |
  'bullet_curtain_usual' |
  'charging_in_sir' |
  'attack_command' |
  'attack_command_defence' |
  'defense_command' |
  'defense_command_attack' |
  'camouflage' |
  'awakening' |
  'fire_support' |
  'charging_order' |
  'seize_opportunity' |
  'bombardment_squadron_command' |
  'elation' |
  'f_armory_deployment' |
  'enhance_output' |
  'scrap_collect' |
  'devour' |
  'electromagnatic_consonance' |
  'max_output_burst' |
  'shot_frost_bolt' |
  'squadron_escort' |
  'forceful_breakthrough' |
  'readying_bombardment' |
  'arrogance_and_anger' |
  'hubris' |
  'hardpoint_mount_equipment' |
  'hardpoint_mount_support' |
  'where_are_you_looking_at' |
  'stealth_camouflage' |
  'overwhelming_cuteness' |
  'observation_data_reception' |
  'guiding_technique' |
  'balance_seeker' |
  'secretive_research' |
  'wreckage_recycling' |
  'new_blasting_tool' |
  'workaholic' |
  'lucky_hit' |
  'power_of_pureblood' |
  'bulk_up' |
  'now_copy_me' |
  'hit_vital_spot' |
  'bravery' |
  'duel_target' |
  'duelist' |
  'second_coming' |
  'command_offense_troop' |
  'command_defense_troop' |
  'cheerleader' |
  'with_flammables' |
  'asceticism' |
  'fanaticism' |
  'bleeding_hole' |
  'night_of_blood_queen' |
  'clear_and_serene' |
  'foresight' |
  'mimesis' |
  'psychic_barrier' |
  'charge_electrically' |
  'high_voltage' |
  'death_blow' |
  'overexcitement' |
  'controlling_excitement' |
  'excitement' |
  'devotion' |
  'fury' |
  'intelligence_collecting' |
  'collection_complete' |
  'parts_acquired' |
  'light_of_sky' |
  'tactical_data_link' |
  'passive_radar' |
  'command_induction' |
  'energy_convert' |
  'electromagnetic_induction_target' |
  'predator' |
  'last_roar' |
  'hunt_preparation' |
  'heat_absorption'
