export type SkillEffectTagStackValue = 1 | 2 | 3 | 5 | 6

export type SkillEffectTag =
  'ignite' |
  'wet' |
  'freeze' |
  'corrosion' |
  'overloaded' |
  'plasma_generator' |
  'frost_storm' |
  'electric_charge' |
  'sadistic_chef' |
  'practice_begins' |
  'output_increase' |
  'targeting' |
  'begin_containment' |
  'counterattack_posture' |
  'cats_hand' |
  'alert_mode' |
  'undying_will' |
  'yummy' |
  'counterattack_initiation' |
  'fire_net_building' |
  'rifled_mortar' |
  'ammo_supplied' |
  'charging_in_sir' |
  'ground_control_artillery' |
  'support_fire' |
  'attack_command' |
  'attack_command_defence' |
  'defense_command' |
  'defense_command_attack' |
  'camouflage' |
  'awakening' |
  'fire_support' |
  'first_aid' |
  'treatment_target_selection' |
  'influence' |
  'unbreakable_tooth' |
  'instinct_to_protect_horde' |
  'tireless_legs' |
  'scenery_in_my_mind' |
  'dreamed_ideals' |
  'charging_order' |
  'seize_opportunity' |
  'rapid_acceleration' |
  'bombardment_squadron_command' |
  'stealth_mode' |
  'elation' |
  'f_armory_deployment' |
  'enhance_output' |
  'scrap_collect' |
  'electromagnatic_consonance' |
  'max_output_burst' |
  'shot_frost_bolt' |
  'forceful_breakthrough' |
  'forced_reconnaissance' |
  'readying_bombardment' |
  'neri_wins' |
  'ho_ho' |
  'anti_air_formation' |
  'arrogance_and_anger' |
  'artillery_command' |
  'reloading' |
  'hardpoint_equipment_armament' |
  'hardpoint_equipment_support' |
  'tactical_air_relay' |
  'where_are_you_looking_at' |
  'stealth_camouflage' |
  'overwhelming_cuteness' |
  'receiving_observation_data' |
  'guiding_technique' |
  'balance_seeker' |
  'secretive_research' |
  'wreckage_recycling' |
  'new_blasting_tool' |
  'workaholic' |
  'lucky_hit' |
  'power_of_pureblood' |
  'bulk_up' |
  'now_copy_me' |
  'gold_forged_through_hundred_refinement' |
  'magical_girl_at_centurys_end' |
  'hit_vital_spot' |
  'bravery' |
  'duel_preparation' |
  'counterattack_preparation' |
  'second_coming' |
  'great_overlord_please_be_careful' |
  'great_overlords_order' |
  'command_offense_troop' |
  'command_defense_troop' |
  'cheerleader' |
  'with_flammables' |
  'asceticism' |
  'fanaticism' |
  'bleeding_hole' |
  'night_of_blood_queen' |
  'clear_and_serene' |
  'foresight' |
  'mimesis' |
  'pre_cooking' |
  'best_desserts' |
  'psychic_barrier' |
  'charge_electrically' |
  'high_voltage' |
  'death_blow' |
  'overexcitement' |
  'controlling_excitement' |
  'excitement' |
  'devotion' |
  'fury' |
  'intelligence_collecting' |
  'collection_complete' |
  'parts_acquired' |
  'light_of_sky' |
  'tenderizer' |
  'caffeine_charged' |
  'nicotine_charged' |
  'smooth' |
  'tactical_data_link' |
  'passive_radar' |
  'command_induction' |
  'energy_convert' |
  'predator' |
  'last_roar' |
  'hunt_preparation' |
  'heat_absorption' |
  'bridle_of_sins'
